// Include the generated bindings
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

fn main() {
    unsafe {
        // Calling a simple C function
        print_hello();

        // Using a C-compatible struct generated by bindgen
        let my_point = Point { x: 10, y: 20 };

        // Calling a C function that takes the struct
        let result = add_points(my_point);

        println!("Result from C add_points: {}", result);
    }
}
